// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function ConnectToServer(arg1) {
  return window['go']['main']['App']['ConnectToServer'](arg1);
}

export function CopyFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['CopyFile'](arg1, arg2, arg3);
}

export function CreateDirectory(arg1, arg2) {
  return window['go']['main']['App']['CreateDirectory'](arg1, arg2);
}

export function DeleteFile(arg1, arg2) {
  return window['go']['main']['App']['DeleteFile'](arg1, arg2);
}

export function DeleteServer(arg1) {
  return window['go']['main']['App']['DeleteServer'](arg1);
}

export function DownloadFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2, arg3);
}

export function GetServers() {
  return window['go']['main']['App']['GetServers']();
}

export function ListDirectory(arg1, arg2) {
  return window['go']['main']['App']['ListDirectory'](arg1, arg2);
}

export function MoveFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveFile'](arg1, arg2, arg3);
}

export function OpenFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenFile'](arg1, arg2, arg3);
}

export function OpenTerminal(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['OpenTerminal'](arg1, arg2, arg3, arg4);
}

export function PasteFromClipboard(arg1, arg2) {
  return window['go']['main']['App']['PasteFromClipboard'](arg1, arg2);
}

export function RenameFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2, arg3);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SaveServer(arg1) {
  return window['go']['main']['App']['SaveServer'](arg1);
}

export function SendTerminalInput(arg1, arg2) {
  return window['go']['main']['App']['SendTerminalInput'](arg1, arg2);
}

export function SetDropTarget(arg1, arg2) {
  return window['go']['main']['App']['SetDropTarget'](arg1, arg2);
}

export function UploadFile(arg1, arg2) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2);
}

export function UploadFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadFiles'](arg1, arg2, arg3);
}
