// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CloseTerminal(arg1:string):Promise<void>;

export function ConnectToServer(arg1:string):Promise<string>;

export function CopyFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateDirectory(arg1:string,arg2:string):Promise<void>;

export function DeleteFile(arg1:string,arg2:string):Promise<void>;

export function DeleteServer(arg1:string):Promise<void>;

export function DownloadFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetServers():Promise<Array<main.ServerConfig>>;

export function ListDirectory(arg1:string,arg2:string):Promise<Array<main.FileInfo>>;

export function MoveFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function OpenFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function OpenTerminal(arg1:string,arg2:string,arg3:number,arg4:number):Promise<string>;

export function PasteFromClipboard(arg1:string,arg2:string):Promise<Array<string>>;

export function RenameFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveServer(arg1:main.ServerConfig):Promise<main.ServerConfig>;

export function SendTerminalInput(arg1:string,arg2:string):Promise<void>;

export function SetDropTarget(arg1:string,arg2:string):Promise<void>;

export function UploadFile(arg1:string,arg2:string):Promise<void>;

export function UploadFiles(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;
